<?php

/**
 * @file
 * Integrates with PayPal Checkout.
 */

define('UC_PAYPAL_CHECKOUT_DEFAULT_BUTTON_CONFIGURATION',
<<<EOD
{
  "layout": "horizontal",
  "fundingicons": true
}
EOD
);

/**
 * Implements hook_menu().
 */
function uc_paypal_checkout_menu() {
  $items = array();

  $items['uc_paypal_checkout/payment-create'] = array(
    'title' => 'Create PayPal payment',
    'description' => 'Creates a PayPal payment with the PayPal Checkout API.',
    'page callback' => 'uc_paypal_checkout_create_payment',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'uc_paypal_checkout.pages.inc',
  );

  $items['uc_paypal_checkout/payment-execute'] = array(
    'title' => 'Execute a PayPal payment',
    'description' => 'Executes a PayPal payment with the PayPal Checkout API.',
    'page callback' => 'uc_paypal_checkout_execute_payment',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'uc_paypal_checkout.pages.inc',
  );

  $items['uc_paypal_checkout/payment-failed'] = array(
    'title' => 'Handle a failed payment',
    'page callback' => 'uc_paypal_checkout_payment_failed',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'uc_paypal_checkout.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_uc_payment_method().
 */
function uc_paypal_checkout_uc_payment_method() {
  $methods = array();

  $methods[] = array(
    'id' => 'paypal_checkout',
    'name' => t('PayPal Checkout'),
    'title' => t('PayPal Checkout'),
    'review' => t('PayPal Checkout'),
    'desc' => t('Complete orders through PayPal Checkout.'),
    'callback' => 'uc_paypal_checkout_payment_method',
    'weight' => 1,
    'checkout' => FALSE,
    'no_gateway' => TRUE,
  );

  return $methods;
}

/**
 * Handles the PayPal Checkout payment method.
 */
function uc_paypal_checkout_payment_method($op, &$order) {
  switch ($op) {
    case 'settings':
      $form['api'] = array(
        '#type' => 'fieldset',
        '#title' => t('PayPal Checkout REST API settings'),
      );
      $form['api']['uc_paypal_checkout_api_url'] = array(
        '#type' => 'textfield',
        '#title' => t('PayPal Checkout API URL'),
        '#required' => TRUE,
        '#description' => t('The URL to the PayPal Checkout REST API including version number (example: https://api.sandbox.paypal.com/v1).'),
        '#default_value' => variable_get('uc_paypal_checkout_api_url', ''),
      );
      $form['api']['uc_paypal_checkout_api_env'] = array(
        '#type' => 'radios',
        '#options' => array(
          'sandbox' => 'sandbox',
          'production' => 'production',
        ),
        '#title' => t('Environment'),
        '#default_value' => variable_get('uc_paypal_checkout_api_env', 'sandbox'),
      );
      $form['api']['uc_paypal_checkout_api_client'] = array(
        '#type' => 'textfield',
        '#title' => t('Client ID'),
        '#required' => TRUE,
        '#default_value' => variable_get('uc_paypal_checkout_api_client', ''),
      );
      $form['api']['uc_paypal_checkout_api_secret'] = array(
        '#type' => 'textfield',
        '#title' => t('Secret'),
        '#required' => TRUE,
        '#default_value' => variable_get('uc_paypal_checkout_api_secret', ''),
      );
      $form['uc_paypal_checkout_locale'] = array(
        '#type' => 'textfield',
        '#title' => t('Locale'),
        '#description' => t('The locale code of the country and language to use when displaying the button.'),
        '#default_value' => variable_get('uc_paypal_checkout_button_locale', 'en_US'),
      );
      $form['uc_paypal_checkout_button_style'] = array(
        '#type' => 'textarea',
        '#title' => t('Button Style'),
        '#default_value' => variable_get('uc_paypal_checkout_button_style', UC_PAYPAL_CHECKOUT_DEFAULT_BUTTON_CONFIGURATION),
        '#description' => t(
          'Enter valid JSON containing button style configuration properties. See the !link for documentation concerning supported configuration properties. %warning',
          array(
            '!link' => l(t('button styles documentation'), 'https://developer.paypal.com/docs/checkout/how-to/customize-button/#button-styles'),
            '%warning' => 'NOTE: some configuration options are not compatible. If the PayPal Checkout button disappears after a style configuration change, this is likely the reason.',
          )
        ),
      );

      $form['#validate'][] = 'uc_paypal_checkout_payment_method_settings_validate';

      return $form;
  }
}

/**
 * Form validation for the Paypal Checkout method settings form.
 */
function uc_paypal_checkout_payment_method_settings_validate($form, &$form_state) {
  if (is_null(json_decode($form_state['values']['uc_paypal_checkout_button_style']))) {
    form_set_error('uc_paypal_checkout_button_style', t('You must enter valid JSON'));
  }
}

/**
 * Generates PayPal Checkout button settings from configuration.
 */
function uc_paypal_checkout_get_settings() {
  return array(
    'env' => variable_get('uc_paypal_checkout_api_env', 'sandbox'),
    'locale' => variable_get('uc_paypal_checkout_locale', 'en_US'),
    'buttonStyle' => json_decode(variable_get('uc_paypal_checkout_button_configuration', UC_PAYPAL_CHECKOUT_DEFAULT_BUTTON_CONFIGURATION)),
    'urls' => array(
      'error' => url('uc_paypal_checkout/payment-failed'),
      'cart' => url('cart'),
      'checkoutComplete' => url('cart/checkout/complete'),
      'paymentCreate' => url('uc_paypal_checkout/payment-create'),
      'paymentExecute' => url('uc_paypal_checkout/payment-execute'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter() for uc_cart_view_form().
 */
function uc_paypal_checkout_form_uc_cart_checkout_review_form_alter(&$form, &$form_state, $form_id) {
  $order = uc_order_load(intval($_SESSION['cart_order']));

  if ($order->payment_method === 'paypal_checkout') {
    $form['actions']['submit']['#access'] = FALSE;
    $form['actions']['paypal_checkout'] = array(
      '#weight' => 999,
      '#markup' => '<div id="paypal-button"></div>',
      '#attached' => array(
        'js' => array(
          array(
            'data' => array(
              'ucPaypalCheckout' => uc_paypal_checkout_get_settings(),
            ),
            'type' => 'setting',
          ),
          array(
            'data' => 'https://www.paypalobjects.com/api/checkout.js',
            'type' => 'external',
          ),
          array(
            'data' => drupal_get_path('module', 'uc_paypal_checkout') . '/js/paypal-button.js',
            'type' => 'file',
          ),
        ),
      ),
    );
  }

  return $form;
}

/**
 * Makes a request to the PayPal REST API during the PayPal Checkout flow.
 *
 * @param string $path
 *   The URL path for the request excluding the API version (example:
 *   "/payments/payment").
 * @param string $method
 *   The HTTP method of the request.
 * @param array|object $body
 *   The body to send with the request.
 *
 * @return object
 *   The API response from the PayPal REST API.
 */
function uc_paypal_checkout_api_request($path, $method, $body) {
  $curl = curl_init();

  $options = array(
    CURLOPT_URL => variable_get('uc_paypal_checkout_api_url') . $path,
    CURLOPT_RETURNTRANSFER => TRUE,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => $method,
    CURLOPT_USERPWD => variable_get('uc_paypal_checkout_api_client') . ':' . variable_get('uc_paypal_checkout_api_secret'),
    CURLOPT_HTTPHEADER => array(
      "Cache-Control: no-cache",
      "Content-Type: application/json",
    ),
  );

  if (isset($body) && !empty($body)) {
    $options[CURLOPT_POSTFIELDS] = json_encode($body);
  }

  curl_setopt_array($curl, $options);

  $response = curl_exec($curl);
  if ($error = curl_error($curl)) {
    watchdog('uc_paypal_checkout', '!error', array('!error' => $error), WATCHDOG_ERROR);
    drupal_goto('uc_paypal_checkout/payment-failed');
  }

  curl_close($curl);

  return $response;
}
